# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/common/tracing_service_capabilities.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/common/tracing_service_capabilities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.common import observable_events_pb2 as protos_dot_perfetto_dot_common_dot_observable__events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9protos/perfetto/common/tracing_service_capabilities.proto\x12\x0fperfetto.protos\x1a.protos/perfetto/common/observable_events.proto\"\xc0\x01\n\x1aTracingServiceCapabilities\x12\x1e\n\x16has_query_capabilities\x18\x01 \x01(\x08\x12\x41\n\x11observable_events\x18\x02 \x03(\x0e\x32&.perfetto.protos.ObservableEvents.Type\x12$\n\x1chas_trace_config_output_path\x18\x03 \x01(\x08\x12\x19\n\x11has_clone_session\x18\x04 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.common.tracing_service_capabilities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACINGSERVICECAPABILITIES']._serialized_start=127
  _globals['_TRACINGSERVICECAPABILITIES']._serialized_end=319
# @@protoc_insertion_point(module_scope)
