# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/graphics/pixelformat.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/graphics/pixelformat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8protos/perfetto/trace/android/graphics/pixelformat.proto\x12\x0fperfetto.protos\"\xcb\x01\n\x10PixelFormatProto\"\xb6\x01\n\x06\x46ormat\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x18\n\x0bTRANSLUCENT\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x18\n\x0bTRANSPARENT\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x13\n\x06OPAQUE\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\r\n\tRGBA_8888\x10\x01\x12\r\n\tRGBX_8888\x10\x02\x12\x0b\n\x07RGB_888\x10\x03\x12\x0b\n\x07RGB_565\x10\x04\x12\x0c\n\x08RGBA_F16\x10\x16\x12\x10\n\x0cRGBA_1010102\x10+')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.graphics.pixelformat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIXELFORMATPROTO']._serialized_start=78
  _globals['_PIXELFORMATPROTO']._serialized_end=281
  _globals['_PIXELFORMATPROTO_FORMAT']._serialized_start=99
  _globals['_PIXELFORMATPROTO_FORMAT']._serialized_end=281
# @@protoc_insertion_point(module_scope)
