# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/chrome/chrome_trace_packet.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/chrome/chrome_trace_packet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.common import trace_stats_pb2 as protos_dot_perfetto_dot_common_dot_trace__stats__pb2
from protos.perfetto.config import trace_config_pb2 as protos_dot_perfetto_dot_config_dot_trace__config__pb2
from protos.perfetto.trace.chrome import chrome_trace_event_pb2 as protos_dot_perfetto_dot_trace_dot_chrome_dot_chrome__trace__event__pb2
from protos.perfetto.trace.chrome import chrome_trigger_pb2 as protos_dot_perfetto_dot_trace_dot_chrome_dot_chrome__trigger__pb2
from protos.perfetto.trace import clock_snapshot_pb2 as protos_dot_perfetto_dot_trace_dot_clock__snapshot__pb2
from protos.perfetto.trace.interned_data import interned_data_pb2 as protos_dot_perfetto_dot_trace_dot_interned__data_dot_interned__data__pb2
from protos.perfetto.trace.profiling import profile_packet_pb2 as protos_dot_perfetto_dot_trace_dot_profiling_dot_profile__packet__pb2
from protos.perfetto.trace.profiling import profile_common_pb2 as protos_dot_perfetto_dot_trace_dot_profiling_dot_profile__common__pb2
from protos.perfetto.trace.track_event import process_descriptor_pb2 as protos_dot_perfetto_dot_trace_dot_track__event_dot_process__descriptor__pb2
from protos.perfetto.trace.track_event import thread_descriptor_pb2 as protos_dot_perfetto_dot_trace_dot_track__event_dot_thread__descriptor__pb2
from protos.perfetto.trace.track_event import track_event_pb2 as protos_dot_perfetto_dot_trace_dot_track__event_dot_track__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6protos/perfetto/trace/chrome/chrome_trace_packet.proto\x12\x0fperfetto.protos\x1a(protos/perfetto/common/trace_stats.proto\x1a)protos/perfetto/config/trace_config.proto\x1a\x35protos/perfetto/trace/chrome/chrome_trace_event.proto\x1a\x31protos/perfetto/trace/chrome/chrome_trigger.proto\x1a*protos/perfetto/trace/clock_snapshot.proto\x1a\x37protos/perfetto/trace/interned_data/interned_data.proto\x1a\x34protos/perfetto/trace/profiling/profile_packet.proto\x1a\x34protos/perfetto/trace/profiling/profile_common.proto\x1a:protos/perfetto/trace/track_event/process_descriptor.proto\x1a\x39protos/perfetto/trace/track_event/thread_descriptor.proto\x1a\x33protos/perfetto/trace/track_event/track_event.proto\"\x84\x06\n\x11\x43hromeTracePacket\x12\x39\n\rchrome_events\x18\x05 \x01(\x0b\x32\".perfetto.protos.ChromeEventBundle\x12\x36\n\x0e\x63lock_snapshot\x18\x06 \x01(\x0b\x32\x1e.perfetto.protos.ClockSnapshot\x12\x30\n\x0btrack_event\x18\x0b \x01(\x0b\x32\x1b.perfetto.protos.TrackEvent\x12>\n\x12process_descriptor\x18+ \x01(\x0b\x32\".perfetto.protos.ProcessDescriptor\x12<\n\x11thread_descriptor\x18, \x01(\x0b\x32!.perfetto.protos.ThreadDescriptor\x12I\n\x18streaming_profile_packet\x18\x36 \x01(\x0b\x32\'.perfetto.protos.StreamingProfilePacket\x12\x45\n\x16profiled_frame_symbols\x18\x37 \x01(\x0b\x32%.perfetto.protos.ProfiledFrameSymbols\x12\x36\n\x0e\x63hrome_trigger\x18m \x01(\x0b\x32\x1e.perfetto.protos.ChromeTrigger\x12\x32\n\x0ctrace_config\x18! \x01(\x0b\x32\x1c.perfetto.protos.TraceConfig\x12\x30\n\x0btrace_stats\x18# \x01(\x0b\x32\x1b.perfetto.protos.TraceStats\x12\"\n\x1atrusted_packet_sequence_id\x18\n \x01(\r\x12\x34\n\rinterned_data\x18\x0c \x01(\x0b\x32\x1d.perfetto.protos.InternedData\x12!\n\x19incremental_state_cleared\x18) \x01(\x08\x12\x1f\n\x17previous_packet_dropped\x18* \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.chrome.chrome_trace_packet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHROMETRACEPACKET']._serialized_start=648
  _globals['_CHROMETRACEPACKET']._serialized_end=1420
# @@protoc_insertion_point(module_scope)
