# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/ad_services_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/ad_services_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8protos/perfetto/metrics/android/ad_services_metric.proto\x12\x0fperfetto.protos\"\xc8\x02\n\x12\x41\x64ServicesUiMetric\x12-\n%common_service_initialization_latency\x18\x01 \x01(\x01\x12/\n\'common_service_permission_check_latency\x18\x02 \x01(\x01\x12-\n%common_service_ux_engine_flow_latency\x18\x03 \x01(\x01\x12&\n\x1emain_activity_creation_latency\x18\x04 \x01(\x01\x12.\n&consent_manager_initialization_latency\x18\x05 \x01(\x01\x12$\n\x1c\x63onsent_manager_read_latency\x18\x06 \x01(\x01\x12%\n\x1d\x63onsent_manager_write_latency\x18\x07 \x01(\x01\"\'\n\x14\x41\x64ServicesAdIdMetric\x12\x0f\n\x07latency\x18\x01 \x01(\x01\"+\n\x18\x41\x64ServicesAppSetIdMetric\x12\x0f\n\x07latency\x18\x01 \x01(\x01\"\xf0\x01\n\x1dOnDevicePersonalizationMetric\x12/\n\'managing_service_initialization_latency\x18\x01 \x01(\x01\x12-\n%service_delegate_execute_flow_latency\x18\x02 \x01(\x01\x12\x38\n0service_delegate_request_surface_package_latency\x18\x03 \x01(\x01\x12\x35\n-service_delegate_register_web_trigger_latency\x18\x04 \x01(\x01\"\x91\x02\n\x10\x41\x64ServicesMetric\x12\x36\n\tui_metric\x18\x01 \x03(\x0b\x32#.perfetto.protos.AdServicesUiMetric\x12;\n\x0c\x61\x64_id_metric\x18\x02 \x03(\x0b\x32%.perfetto.protos.AdServicesAdIdMetric\x12\x44\n\x11\x61pp_set_id_metric\x18\x03 \x03(\x0b\x32).perfetto.protos.AdServicesAppSetIdMetric\x12\x42\n\nodp_metric\x18\x04 \x03(\x0b\x32..perfetto.protos.OnDevicePersonalizationMetric')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.ad_services_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADSERVICESUIMETRIC']._serialized_start=78
  _globals['_ADSERVICESUIMETRIC']._serialized_end=406
  _globals['_ADSERVICESADIDMETRIC']._serialized_start=408
  _globals['_ADSERVICESADIDMETRIC']._serialized_end=447
  _globals['_ADSERVICESAPPSETIDMETRIC']._serialized_start=449
  _globals['_ADSERVICESAPPSETIDMETRIC']._serialized_end=492
  _globals['_ONDEVICEPERSONALIZATIONMETRIC']._serialized_start=495
  _globals['_ONDEVICEPERSONALIZATIONMETRIC']._serialized_end=735
  _globals['_ADSERVICESMETRIC']._serialized_start=738
  _globals['_ADSERVICESMETRIC']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
