# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/android_anomaly_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/android_anomaly_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<protos/perfetto/metrics/android/android_anomaly_metric.proto\x12\x0fperfetto.protos\"\xdb\x03\n\x14\x41ndroidAnomalyMetric\x12<\n\x06\x62inder\x18\x01 \x01(\x0b\x32,.perfetto.protos.AndroidAnomalyMetric.Binder\x1a|\n\x0eProcessAnomaly\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x38\n\x04unit\x18\x03 \x01(\x0e\x32*.perfetto.protos.AndroidAnomalyMetric.Unit\x12\r\n\x05value\x18\x04 \x01(\r\x1a\xd2\x01\n\x06\x42inder\x12\x63\n%max_incoming_process_count_per_second\x18\x01 \x03(\x0b\x32\x34.perfetto.protos.AndroidAnomalyMetric.ProcessAnomaly\x12\x63\n%max_outgoing_process_count_per_second\x18\x02 \x03(\x0b\x32\x34.perfetto.protos.AndroidAnomalyMetric.ProcessAnomaly\"2\n\x04Unit\x12\x14\n\x10UNIT_UNSPECIFIED\x10\x00\x12\x14\n\x10\x43OUNT_PER_SECOND\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.android_anomaly_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDANOMALYMETRIC']._serialized_start=82
  _globals['_ANDROIDANOMALYMETRIC']._serialized_end=557
  _globals['_ANDROIDANOMALYMETRIC_PROCESSANOMALY']._serialized_start=168
  _globals['_ANDROIDANOMALYMETRIC_PROCESSANOMALY']._serialized_end=292
  _globals['_ANDROIDANOMALYMETRIC_BINDER']._serialized_start=295
  _globals['_ANDROIDANOMALYMETRIC_BINDER']._serialized_end=505
  _globals['_ANDROIDANOMALYMETRIC_UNIT']._serialized_start=507
  _globals['_ANDROIDANOMALYMETRIC_UNIT']._serialized_end=557
# @@protoc_insertion_point(module_scope)
