# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/android_broadcasts_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/android_broadcasts_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?protos/perfetto/metrics/android/android_broadcasts_metric.proto\x12\x0fperfetto.protos\"\xf1\x04\n\x17\x41ndroidBroadcastsMetric\x12\x63\n\x17process_count_by_intent\x18\x01 \x03(\x0b\x32\x42.perfetto.protos.AndroidBroadcastsMetric.BroadcastCountAggregation\x12\x66\n\x1a\x62roadcast_count_by_process\x18\x02 \x03(\x0b\x32\x42.perfetto.protos.AndroidBroadcastsMetric.BroadcastCountAggregation\x12n\n\x1f\x62rodcast_duration_agg_by_intent\x18\x03 \x03(\x0b\x32\x45.perfetto.protos.AndroidBroadcastsMetric.BroadcastDurationAggregation\x12o\n brodcast_duration_agg_by_process\x18\x04 \x03(\x0b\x32\x45.perfetto.protos.AndroidBroadcastsMetric.BroadcastDurationAggregation\x1a\x38\n\x19\x42roadcastCountAggregation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x1an\n\x1c\x42roadcastDurationAggregation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x61vg_duration\x18\x02 \x01(\x01\x12\x14\n\x0cmax_duration\x18\x03 \x01(\x03\x12\x14\n\x0csum_duration\x18\x04 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.android_broadcasts_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDBROADCASTSMETRIC']._serialized_start=85
  _globals['_ANDROIDBROADCASTSMETRIC']._serialized_end=710
  _globals['_ANDROIDBROADCASTSMETRIC_BROADCASTCOUNTAGGREGATION']._serialized_start=542
  _globals['_ANDROIDBROADCASTSMETRIC_BROADCASTCOUNTAGGREGATION']._serialized_end=598
  _globals['_ANDROIDBROADCASTSMETRIC_BROADCASTDURATIONAGGREGATION']._serialized_start=600
  _globals['_ANDROIDBROADCASTSMETRIC_BROADCASTDURATIONAGGREGATION']._serialized_end=710
# @@protoc_insertion_point(module_scope)
