# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/android_oom_adjuster_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/android_oom_adjuster_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAprotos/perfetto/metrics/android/android_oom_adjuster_metric.proto\x12\x0fperfetto.protos\"\xb7\x08\n\x18\x41ndroidOomAdjusterMetric\x12t\n%oom_adjuster_transition_counts_global\x18\x01 \x03(\x0b\x32\x45.perfetto.protos.AndroidOomAdjusterMetric.OomAdjusterTransitionCounts\x12x\n)oom_adjuster_transition_counts_by_process\x18\x02 \x03(\x0b\x32\x45.perfetto.protos.AndroidOomAdjusterMetric.OomAdjusterTransitionCounts\x12\x7f\n0oom_adjuster_transition_counts_by_oom_adj_reason\x18\x03 \x03(\x0b\x32\x45.perfetto.protos.AndroidOomAdjusterMetric.OomAdjusterTransitionCounts\x12u\n\"oom_adj_bucket_duration_agg_global\x18\x04 \x03(\x0b\x32I.perfetto.protos.AndroidOomAdjusterMetric.OomAdjBucketDurationAggregation\x12y\n&oom_adj_bucket_duration_agg_by_process\x18\x05 \x03(\x0b\x32I.perfetto.protos.AndroidOomAdjusterMetric.OomAdjBucketDurationAggregation\x12\x61\n\x14oom_adj_duration_agg\x18\x06 \x03(\x0b\x32\x43.perfetto.protos.AndroidOomAdjusterMetric.OomAdjDurationAggregation\x1a\x63\n\x1bOomAdjusterTransitionCounts\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nsrc_bucket\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65st_bucket\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x03\x1aR\n\x1fOomAdjBucketDurationAggregation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\t\x12\x11\n\ttotal_dur\x18\x03 \x01(\x03\x1a\x9b\x01\n\x19OomAdjDurationAggregation\x12\x17\n\x0fmin_oom_adj_dur\x18\x01 \x01(\x03\x12\x17\n\x0fmax_oom_adj_dur\x18\x02 \x01(\x03\x12\x17\n\x0f\x61vg_oom_adj_dur\x18\x03 \x01(\x01\x12\x1b\n\x13oom_adj_event_count\x18\x04 \x01(\x03\x12\x16\n\x0eoom_adj_reason\x18\x05 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.android_oom_adjuster_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDOOMADJUSTERMETRIC']._serialized_start=87
  _globals['_ANDROIDOOMADJUSTERMETRIC']._serialized_end=1166
  _globals['_ANDROIDOOMADJUSTERMETRIC_OOMADJUSTERTRANSITIONCOUNTS']._serialized_start=825
  _globals['_ANDROIDOOMADJUSTERMETRIC_OOMADJUSTERTRANSITIONCOUNTS']._serialized_end=924
  _globals['_ANDROIDOOMADJUSTERMETRIC_OOMADJBUCKETDURATIONAGGREGATION']._serialized_start=926
  _globals['_ANDROIDOOMADJUSTERMETRIC_OOMADJBUCKETDURATIONAGGREGATION']._serialized_end=1008
  _globals['_ANDROIDOOMADJUSTERMETRIC_OOMADJDURATIONAGGREGATION']._serialized_start=1011
  _globals['_ANDROIDOOMADJUSTERMETRIC_OOMADJDURATIONAGGREGATION']._serialized_end=1166
# @@protoc_insertion_point(module_scope)
