# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/android_frame_timeline_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/android_frame_timeline_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import process_metadata_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_process__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCprotos/perfetto/metrics/android/android_frame_timeline_metric.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/metrics/android/process_metadata.proto\"\x90\x08\n\x1a\x41ndroidFrameTimelineMetric\x12\x14\n\x0ctotal_frames\x18\x04 \x01(\x03\x12\x19\n\x11missed_app_frames\x18\x05 \x01(\x03\x12\x16\n\x0e\x64ropped_frames\x18\x06 \x01(\x03\x12M\n\x07process\x18\x02 \x03(\x0b\x32<.perfetto.protos.AndroidFrameTimelineMetric.ProcessBreakdown\x12N\n\njank_types\x18\x07 \x03(\x0b\x32:.perfetto.protos.AndroidFrameTimelineMetric.JankTypeMetric\x1a\xec\x01\n\x0eJankTypeMetric\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x13\n\x0btotal_count\x18\x02 \x01(\x03\x12!\n\x19present_unspecified_count\x18\x03 \x01(\x03\x12\x1d\n\x15present_on_time_count\x18\x04 \x01(\x03\x12\x1a\n\x12present_late_count\x18\x05 \x01(\x03\x12\x1b\n\x13present_early_count\x18\x06 \x01(\x03\x12\x1d\n\x15present_dropped_count\x18\x07 \x01(\x03\x12\x1d\n\x15present_unknown_count\x18\x08 \x01(\x03\x1a\x94\x04\n\x10ProcessBreakdown\x12\x38\n\x07process\x18\x03 \x01(\x0b\x32\'.perfetto.protos.AndroidProcessMetadata\x12\x14\n\x0ctotal_frames\x18\x04 \x01(\x03\x12\x15\n\rmissed_frames\x18\x05 \x01(\x03\x12\x19\n\x11missed_app_frames\x18\x06 \x01(\x03\x12\x18\n\x10missed_sf_frames\x18\x07 \x01(\x03\x12\x15\n\rframe_dur_max\x18\x08 \x01(\x03\x12\x15\n\rframe_dur_avg\x18\t \x01(\x03\x12\x15\n\rframe_dur_p50\x18\n \x01(\x03\x12\x15\n\rframe_dur_p90\x18\x0b \x01(\x03\x12\x15\n\rframe_dur_p95\x18\x0c \x01(\x03\x12\x15\n\rframe_dur_p99\x18\r \x01(\x03\x12\x18\n\x10\x66rame_dur_ms_p50\x18\x0e \x01(\x01\x12\x18\n\x10\x66rame_dur_ms_p90\x18\x0f \x01(\x01\x12\x18\n\x10\x66rame_dur_ms_p95\x18\x10 \x01(\x01\x12\x18\n\x10\x66rame_dur_ms_p99\x18\x11 \x01(\x01\x12\x16\n\x0e\x64ropped_frames\x18\x12 \x01(\x03\x12N\n\njank_types\x18\x13 \x03(\x0b\x32:.perfetto.protos.AndroidFrameTimelineMetric.JankTypeMetricJ\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x01\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.android_frame_timeline_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDFRAMETIMELINEMETRIC']._serialized_start=145
  _globals['_ANDROIDFRAMETIMELINEMETRIC']._serialized_end=1185
  _globals['_ANDROIDFRAMETIMELINEMETRIC_JANKTYPEMETRIC']._serialized_start=408
  _globals['_ANDROIDFRAMETIMELINEMETRIC_JANKTYPEMETRIC']._serialized_end=644
  _globals['_ANDROIDFRAMETIMELINEMETRIC_PROCESSBREAKDOWN']._serialized_start=647
  _globals['_ANDROIDFRAMETIMELINEMETRIC_PROCESSBREAKDOWN']._serialized_end=1179
# @@protoc_insertion_point(module_scope)
