# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/android_boot_unagg.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/android_boot_unagg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import app_process_starts_metric_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_app__process__starts__metric__pb2
from protos.perfetto.metrics.android import android_garbage_collection_unagg_metric_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_android__garbage__collection__unagg__metric__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8protos/perfetto/metrics/android/android_boot_unagg.proto\x12\x0fperfetto.protos\x1a?protos/perfetto/metrics/android/app_process_starts_metric.proto\x1aMprotos/perfetto/metrics/android/android_garbage_collection_unagg_metric.proto\"\xc7\x01\n\x10\x41ndroidBootUnagg\x12X\n android_app_process_start_metric\x18\x01 \x01(\x0b\x32..perfetto.protos.AndroidAppProcessStartsMetric\x12Y\n\x1b\x61ndroid_post_boot_gc_metric\x18\x02 \x01(\x0b\x32\x34.perfetto.protos.AndroidGarbageCollectionUnaggMetric')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.android_boot_unagg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDBOOTUNAGG']._serialized_start=222
  _globals['_ANDROIDBOOTUNAGG']._serialized_end=421
# @@protoc_insertion_point(module_scope)
