# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/camera_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/camera_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3protos/perfetto/metrics/android/camera_metric.proto\x12\x0fperfetto.protos\"\x8d\x01\n\x13\x41ndroidCameraMetric\x12\x44\n\x0egc_rss_and_dma\x18\x01 \x01(\x0b\x32,.perfetto.protos.AndroidCameraMetric.Counter\x1a\x30\n\x07\x43ounter\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x12\x0b\n\x03\x61vg\x18\x03 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.camera_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDCAMERAMETRIC']._serialized_start=73
  _globals['_ANDROIDCAMERAMETRIC']._serialized_end=214
  _globals['_ANDROIDCAMERAMETRIC_COUNTER']._serialized_start=166
  _globals['_ANDROIDCAMERAMETRIC_COUNTER']._serialized_end=214
# @@protoc_insertion_point(module_scope)
