# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/camera_unagg_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/camera_unagg_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9protos/perfetto/metrics/android/camera_unagg_metric.proto\x12\x0fperfetto.protos\"\xee\x01\n\x1f\x41ndroidCameraUnaggregatedMetric\x12N\n\x0egc_rss_and_dma\x18\x01 \x03(\x0b\x32\x36.perfetto.protos.AndroidCameraUnaggregatedMetric.Value\x1a{\n\x05Value\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x13\n\x0bgca_rss_val\x18\x02 \x01(\x01\x12\x13\n\x0bhal_rss_val\x18\x03 \x01(\x01\x12\x1c\n\x14\x63\x61meraserver_rss_val\x18\x04 \x01(\x01\x12\x0f\n\x07\x64ma_val\x18\x05 \x01(\x01\x12\r\n\x05value\x18\x06 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.camera_unagg_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDCAMERAUNAGGREGATEDMETRIC']._serialized_start=79
  _globals['_ANDROIDCAMERAUNAGGREGATEDMETRIC']._serialized_end=317
  _globals['_ANDROIDCAMERAUNAGGREGATEDMETRIC_VALUE']._serialized_start=194
  _globals['_ANDROIDCAMERAUNAGGREGATEDMETRIC_VALUE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
