# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/codec_metrics.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/codec_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import cpu_metric_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_cpu__metric__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3protos/perfetto/metrics/android/codec_metrics.proto\x12\x0fperfetto.protos\x1a\x30protos/perfetto/metrics/android/cpu_metric.proto\"\x97\x04\n\x13\x41ndroidCodecMetrics\x12@\n\tcpu_usage\x18\x01 \x03(\x0b\x32-.perfetto.protos.AndroidCodecMetrics.CpuUsage\x12J\n\x0e\x63odec_function\x18\x02 \x03(\x0b\x32\x32.perfetto.protos.AndroidCodecMetrics.CodecFunction\x1aK\n\x06\x44\x65tail\x12\x13\n\x0bthread_name\x18\x01 \x01(\t\x12\x14\n\x0ctotal_cpu_ns\x18\x02 \x01(\x03\x12\x16\n\x0erunning_cpu_ns\x18\x03 \x01(\x03\x1ax\n\rCodecFunction\x12\x14\n\x0c\x63odec_string\x18\x01 \x01(\t\x12\x14\n\x0cprocess_name\x18\x02 \x01(\t\x12;\n\x06\x64\x65tail\x18\x03 \x01(\x0b\x32+.perfetto.protos.AndroidCodecMetrics.Detail\x1a\xaa\x01\n\x08\x43puUsage\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\x12\x13\n\x0bthread_name\x18\x02 \x01(\t\x12\x15\n\rthread_cpu_ns\x18\x06 \x01(\x03\x12\x13\n\x0bnum_threads\x18\x04 \x01(\r\x12\x41\n\tcore_data\x18\x05 \x03(\x0b\x32..perfetto.protos.AndroidCpuMetric.CoreTypeDataJ\x04\x08\x03\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.codec_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDCODECMETRICS']._serialized_start=123
  _globals['_ANDROIDCODECMETRICS']._serialized_end=658
  _globals['_ANDROIDCODECMETRICS_DETAIL']._serialized_start=288
  _globals['_ANDROIDCODECMETRICS_DETAIL']._serialized_end=363
  _globals['_ANDROIDCODECMETRICS_CODECFUNCTION']._serialized_start=365
  _globals['_ANDROIDCODECMETRICS_CODECFUNCTION']._serialized_end=485
  _globals['_ANDROIDCODECMETRICS_CPUUSAGE']._serialized_start=488
  _globals['_ANDROIDCODECMETRICS_CPUUSAGE']._serialized_end=658
# @@protoc_insertion_point(module_scope)
