# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/cpu_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/cpu_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import process_metadata_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_process__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protos/perfetto/metrics/android/cpu_metric.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/metrics/android/process_metadata.proto\"\x9f\x07\n\x10\x41ndroidCpuMetric\x12?\n\x0cprocess_info\x18\x01 \x03(\x0b\x32).perfetto.protos.AndroidCpuMetric.Process\x1ap\n\x07Metrics\x12\x0f\n\x07mcycles\x18\x01 \x01(\x03\x12\x12\n\nruntime_ns\x18\x02 \x01(\x03\x12\x14\n\x0cmin_freq_khz\x18\x03 \x01(\x03\x12\x14\n\x0cmax_freq_khz\x18\x04 \x01(\x03\x12\x14\n\x0c\x61vg_freq_khz\x18\x05 \x01(\x03\x1aX\n\x08\x43oreData\x12\n\n\x02id\x18\x01 \x01(\r\x12:\n\x07metrics\x18\x06 \x01(\x0b\x32).perfetto.protos.AndroidCpuMetric.MetricsJ\x04\x08\x02\x10\x06\x1aX\n\x0c\x43oreTypeData\x12\x0c\n\x04type\x18\x01 \x01(\t\x12:\n\x07metrics\x18\x02 \x01(\x0b\x32).perfetto.protos.AndroidCpuMetric.Metrics\x1a\xd5\x01\n\x06Thread\x12\x0c\n\x04name\x18\x01 \x01(\t\x12:\n\x07metrics\x18\x04 \x01(\x0b\x32).perfetto.protos.AndroidCpuMetric.Metrics\x12\x38\n\x04\x63ore\x18\x02 \x03(\x0b\x32*.perfetto.protos.AndroidCpuMetric.CoreData\x12\x41\n\tcore_type\x18\x05 \x03(\x0b\x32..perfetto.protos.AndroidCpuMetric.CoreTypeDataJ\x04\x08\x03\x10\x04\x1a\xcb\x02\n\x07Process\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x38\n\x07process\x18\x08 \x01(\x0b\x32\'.perfetto.protos.AndroidProcessMetadata\x12:\n\x07metrics\x18\x04 \x01(\x0b\x32).perfetto.protos.AndroidCpuMetric.Metrics\x12\x39\n\x07threads\x18\x06 \x03(\x0b\x32(.perfetto.protos.AndroidCpuMetric.Thread\x12\x38\n\x04\x63ore\x18\x07 \x03(\x0b\x32*.perfetto.protos.AndroidCpuMetric.CoreData\x12\x41\n\tcore_type\x18\x05 \x03(\x0b\x32..perfetto.protos.AndroidCpuMetric.CoreTypeDataJ\x04\x08\x03\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.cpu_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDCPUMETRIC']._serialized_start=126
  _globals['_ANDROIDCPUMETRIC']._serialized_end=1053
  _globals['_ANDROIDCPUMETRIC_METRICS']._serialized_start=211
  _globals['_ANDROIDCPUMETRIC_METRICS']._serialized_end=323
  _globals['_ANDROIDCPUMETRIC_COREDATA']._serialized_start=325
  _globals['_ANDROIDCPUMETRIC_COREDATA']._serialized_end=413
  _globals['_ANDROIDCPUMETRIC_CORETYPEDATA']._serialized_start=415
  _globals['_ANDROIDCPUMETRIC_CORETYPEDATA']._serialized_end=503
  _globals['_ANDROIDCPUMETRIC_THREAD']._serialized_start=506
  _globals['_ANDROIDCPUMETRIC_THREAD']._serialized_end=719
  _globals['_ANDROIDCPUMETRIC_PROCESS']._serialized_start=722
  _globals['_ANDROIDCPUMETRIC_PROCESS']._serialized_end=1053
# @@protoc_insertion_point(module_scope)
