# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/display_metrics.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/display_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5protos/perfetto/metrics/android/display_metrics.proto\x12\x0fperfetto.protos\"\xe2\x03\n\x15\x41ndroidDisplayMetrics\x12\x1e\n\x16total_duplicate_frames\x18\x01 \x01(\r\x12\x1f\n\x17\x64uplicate_frames_logged\x18\x02 \x01(\r\x12 \n\x18total_dpu_underrun_count\x18\x03 \x01(\r\x12\x1d\n\x15refresh_rate_switches\x18\x04 \x01(\r\x12R\n\x12refresh_rate_stats\x18\x05 \x03(\x0b\x32\x36.perfetto.protos.AndroidDisplayMetrics.RefreshRateStat\x12S\n\x12update_power_state\x18\x06 \x01(\x0b\x32\x37.perfetto.protos.AndroidDisplayMetrics.UpdatePowerState\x1a\x64\n\x0fRefreshRateStat\x12\x18\n\x10refresh_rate_fps\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x14\n\x0ctotal_dur_ms\x18\x03 \x01(\x01\x12\x12\n\navg_dur_ms\x18\x04 \x01(\x01\x1a\x38\n\x10UpdatePowerState\x12\x1e\n\x16\x61vg_runtime_micro_secs\x18\x02 \x01(\rJ\x04\x08\x01\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.display_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDDISPLAYMETRICS']._serialized_start=75
  _globals['_ANDROIDDISPLAYMETRICS']._serialized_end=557
  _globals['_ANDROIDDISPLAYMETRICS_REFRESHRATESTAT']._serialized_start=399
  _globals['_ANDROIDDISPLAYMETRICS_REFRESHRATESTAT']._serialized_end=499
  _globals['_ANDROIDDISPLAYMETRICS_UPDATEPOWERSTATE']._serialized_start=501
  _globals['_ANDROIDDISPLAYMETRICS_UPDATEPOWERSTATE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
