# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/dma_heap_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/dma_heap_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5protos/perfetto/metrics/android/dma_heap_metric.proto\x12\x0fperfetto.protos\"\x9f\x02\n\x14\x41ndroidDmaHeapMetric\x12\x16\n\x0e\x61vg_size_bytes\x18\x01 \x01(\x01\x12\x16\n\x0emin_size_bytes\x18\x02 \x01(\x01\x12\x16\n\x0emax_size_bytes\x18\x03 \x01(\x01\x12\x1e\n\x16total_alloc_size_bytes\x18\x04 \x01(\x01\x12\x19\n\x11total_delta_bytes\x18\x05 \x01(\x05\x12I\n\rprocess_stats\x18\x06 \x03(\x0b\x32\x32.perfetto.protos.AndroidDmaHeapMetric.ProcessStats\x1a\x39\n\x0cProcessStats\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65lta_bytes\x18\x02 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.dma_heap_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDDMAHEAPMETRIC']._serialized_start=75
  _globals['_ANDROIDDMAHEAPMETRIC']._serialized_end=362
  _globals['_ANDROIDDMAHEAPMETRIC_PROCESSSTATS']._serialized_start=305
  _globals['_ANDROIDDMAHEAPMETRIC_PROCESSSTATS']._serialized_end=362
# @@protoc_insertion_point(module_scope)
