# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/dvfs_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/dvfs_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1protos/perfetto/metrics/android/dvfs_metric.proto\x12\x0fperfetto.protos\"\x96\x02\n\x11\x41ndroidDvfsMetric\x12O\n\x10\x66req_residencies\x18\x01 \x03(\x0b\x32\x35.perfetto.protos.AndroidDvfsMetric.FrequencyResidency\x1aG\n\x08\x42\x61ndStat\x12\x12\n\nfreq_value\x18\x01 \x01(\x05\x12\x12\n\npercentage\x18\x02 \x01(\x01\x12\x13\n\x0b\x64uration_ns\x18\x03 \x01(\x03\x1ag\n\x12\x46requencyResidency\x12\x11\n\tfreq_name\x18\x01 \x01(\t\x12>\n\tband_stat\x18\x02 \x03(\x0b\x32+.perfetto.protos.AndroidDvfsMetric.BandStat')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.dvfs_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDDVFSMETRIC']._serialized_start=71
  _globals['_ANDROIDDVFSMETRIC']._serialized_end=349
  _globals['_ANDROIDDVFSMETRIC_BANDSTAT']._serialized_start=173
  _globals['_ANDROIDDVFSMETRIC_BANDSTAT']._serialized_end=244
  _globals['_ANDROIDDVFSMETRIC_FREQUENCYRESIDENCY']._serialized_start=246
  _globals['_ANDROIDDVFSMETRIC_FREQUENCYRESIDENCY']._serialized_end=349
# @@protoc_insertion_point(module_scope)
