# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/fastrpc_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/fastrpc_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4protos/perfetto/metrics/android/fastrpc_metric.proto\x12\x0fperfetto.protos\"\xde\x01\n\x14\x41ndroidFastrpcMetric\x12\x42\n\tsubsystem\x18\x01 \x03(\x0b\x32/.perfetto.protos.AndroidFastrpcMetric.Subsystem\x1a\x81\x01\n\tSubsystem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x61vg_size_bytes\x18\x02 \x01(\x01\x12\x16\n\x0emin_size_bytes\x18\x03 \x01(\x01\x12\x16\n\x0emax_size_bytes\x18\x04 \x01(\x01\x12\x1e\n\x16total_alloc_size_bytes\x18\x05 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.fastrpc_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDFASTRPCMETRIC']._serialized_start=74
  _globals['_ANDROIDFASTRPCMETRIC']._serialized_end=296
  _globals['_ANDROIDFASTRPCMETRIC_SUBSYSTEM']._serialized_start=167
  _globals['_ANDROIDFASTRPCMETRIC_SUBSYSTEM']._serialized_end=296
# @@protoc_insertion_point(module_scope)
