# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/gpu_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/gpu_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protos/perfetto/metrics/android/gpu_metric.proto\x12\x0fperfetto.protos\"\x96\x04\n\x10\x41ndroidGpuMetric\x12<\n\tprocesses\x18\x01 \x03(\x0b\x32).perfetto.protos.AndroidGpuMetric.Process\x12\x0f\n\x07mem_max\x18\x02 \x01(\x03\x12\x0f\n\x07mem_min\x18\x03 \x01(\x03\x12\x0f\n\x07mem_avg\x18\x04 \x01(\x03\x12G\n\x0c\x66req_metrics\x18\x05 \x03(\x0b\x32\x31.perfetto.protos.AndroidGpuMetric.FrequencyMetric\x1aJ\n\x07Process\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07mem_max\x18\x02 \x01(\x03\x12\x0f\n\x07mem_min\x18\x03 \x01(\x03\x12\x0f\n\x07mem_avg\x18\x04 \x01(\x03\x1a\xfb\x01\n\x0f\x46requencyMetric\x12\x0e\n\x06gpu_id\x18\x01 \x01(\r\x12\x10\n\x08\x66req_max\x18\x02 \x01(\x03\x12\x10\n\x08\x66req_min\x18\x03 \x01(\x03\x12\x10\n\x08\x66req_avg\x18\x04 \x01(\x01\x12Y\n\nused_freqs\x18\x05 \x03(\x0b\x32\x45.perfetto.protos.AndroidGpuMetric.FrequencyMetric.MetricsPerFrequency\x1aG\n\x13MetricsPerFrequency\x12\x0c\n\x04\x66req\x18\x01 \x01(\x03\x12\x0e\n\x06\x64ur_ms\x18\x02 \x01(\x01\x12\x12\n\npercentage\x18\x03 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.gpu_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDGPUMETRIC']._serialized_start=70
  _globals['_ANDROIDGPUMETRIC']._serialized_end=604
  _globals['_ANDROIDGPUMETRIC_PROCESS']._serialized_start=276
  _globals['_ANDROIDGPUMETRIC_PROCESS']._serialized_end=350
  _globals['_ANDROIDGPUMETRIC_FREQUENCYMETRIC']._serialized_start=353
  _globals['_ANDROIDGPUMETRIC_FREQUENCYMETRIC']._serialized_end=604
  _globals['_ANDROIDGPUMETRIC_FREQUENCYMETRIC_METRICSPERFREQUENCY']._serialized_start=533
  _globals['_ANDROIDGPUMETRIC_FREQUENCYMETRIC_METRICSPERFREQUENCY']._serialized_end=604
# @@protoc_insertion_point(module_scope)
