# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/io_unagg_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/io_unagg_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5protos/perfetto/metrics/android/io_unagg_metric.proto\x12\x0fperfetto.protos\"\xfe\x01\n\x15\x41ndroidIoUnaggregated\x12h\n\x1d\x66\x32\x66s_write_unaggregated_stats\x18\x01 \x03(\x0b\x32\x41.perfetto.protos.AndroidIoUnaggregated.F2fsWriteUnaggreagatedStat\x1a{\n\x1a\x46\x32\x66sWriteUnaggreagatedStat\x12\x0b\n\x03tid\x18\x01 \x01(\r\x12\x13\n\x0bthread_name\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\r\x12\x14\n\x0cprocess_name\x18\x04 \x01(\t\x12\x0b\n\x03ino\x18\x05 \x01(\x03\x12\x0b\n\x03\x64\x65v\x18\x06 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.io_unagg_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDIOUNAGGREGATED']._serialized_start=75
  _globals['_ANDROIDIOUNAGGREGATED']._serialized_end=329
  _globals['_ANDROIDIOUNAGGREGATED_F2FSWRITEUNAGGREAGATEDSTAT']._serialized_start=206
  _globals['_ANDROIDIOUNAGGREGATED_F2FSWRITEUNAGGREAGATEDSTAT']._serialized_end=329
# @@protoc_insertion_point(module_scope)
