# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/irq_runtime_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/irq_runtime_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8protos/perfetto/metrics/android/irq_runtime_metric.proto\x12\x0fperfetto.protos\"\xa3\x04\n\x17\x41ndroidIrqRuntimeMetric\x12I\n\x06hw_irq\x18\x01 \x01(\x0b\x32\x39.perfetto.protos.AndroidIrqRuntimeMetric.IrqRuntimeMetric\x12I\n\x06sw_irq\x18\x02 \x01(\x0b\x32\x39.perfetto.protos.AndroidIrqRuntimeMetric.IrqRuntimeMetric\x1a\x35\n\x08IrqSlice\x12\x10\n\x08irq_name\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x01(\x03\x12\x0b\n\x03\x64ur\x18\x03 \x01(\x03\x1aY\n\x0fThresholdMetric\x12\x11\n\tthreshold\x18\x01 \x01(\t\x12\x1c\n\x14over_threshold_count\x18\x02 \x01(\x03\x12\x15\n\ranomaly_ratio\x18\x03 \x01(\x01\x1a\xdf\x01\n\x10IrqRuntimeMetric\x12\x13\n\x0bmax_runtime\x18\x01 \x01(\x03\x12\x13\n\x0btotal_count\x18\x02 \x01(\x03\x12R\n\x10threshold_metric\x18\x03 \x01(\x0b\x32\x38.perfetto.protos.AndroidIrqRuntimeMetric.ThresholdMetric\x12M\n\x12longest_irq_slices\x18\x04 \x03(\x0b\x32\x31.perfetto.protos.AndroidIrqRuntimeMetric.IrqSlice')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.irq_runtime_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDIRQRUNTIMEMETRIC']._serialized_start=78
  _globals['_ANDROIDIRQRUNTIMEMETRIC']._serialized_end=625
  _globals['_ANDROIDIRQRUNTIMEMETRIC_IRQSLICE']._serialized_start=255
  _globals['_ANDROIDIRQRUNTIMEMETRIC_IRQSLICE']._serialized_end=308
  _globals['_ANDROIDIRQRUNTIMEMETRIC_THRESHOLDMETRIC']._serialized_start=310
  _globals['_ANDROIDIRQRUNTIMEMETRIC_THRESHOLDMETRIC']._serialized_end=399
  _globals['_ANDROIDIRQRUNTIMEMETRIC_IRQRUNTIMEMETRIC']._serialized_start=402
  _globals['_ANDROIDIRQRUNTIMEMETRIC_IRQRUNTIMEMETRIC']._serialized_end=625
# @@protoc_insertion_point(module_scope)
