# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/java_heap_class_stats.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/java_heap_class_stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import process_metadata_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_process__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;protos/perfetto/metrics/android/java_heap_class_stats.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/metrics/android/process_metadata.proto\"\x95\x05\n\x12JavaHeapClassStats\x12I\n\x0einstance_stats\x18\x01 \x03(\x0b\x32\x31.perfetto.protos.JavaHeapClassStats.InstanceStats\x1a\xc3\x02\n\tTypeCount\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12\x1b\n\x13is_libcore_or_array\x18\x0c \x01(\x08\x12\x11\n\tobj_count\x18\x02 \x01(\x03\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\x12\x19\n\x11native_size_bytes\x18\x04 \x01(\x03\x12\x1b\n\x13reachable_obj_count\x18\x05 \x01(\x03\x12\x1c\n\x14reachable_size_bytes\x18\x06 \x01(\x03\x12#\n\x1breachable_native_size_bytes\x18\x07 \x01(\x03\x12\x1b\n\x13\x64ominated_obj_count\x18\x08 \x01(\x03\x12\x1c\n\x14\x64ominated_size_bytes\x18\t \x01(\x03\x12#\n\x1b\x64ominated_native_size_bytes\x18\n \x01(\x03J\x04\x08\x0b\x10\x0c\x1aW\n\x06Sample\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x41\n\ntype_count\x18\x02 \x03(\x0b\x32-.perfetto.protos.JavaHeapClassStats.TypeCount\x1a\x94\x01\n\rInstanceStats\x12\x0c\n\x04upid\x18\x01 \x01(\r\x12\x38\n\x07process\x18\x02 \x01(\x0b\x32\'.perfetto.protos.AndroidProcessMetadata\x12;\n\x07samples\x18\x03 \x03(\x0b\x32*.perfetto.protos.JavaHeapClassStats.Sample')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.java_heap_class_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JAVAHEAPCLASSSTATS']._serialized_start=137
  _globals['_JAVAHEAPCLASSSTATS']._serialized_end=798
  _globals['_JAVAHEAPCLASSSTATS_TYPECOUNT']._serialized_start=235
  _globals['_JAVAHEAPCLASSSTATS_TYPECOUNT']._serialized_end=558
  _globals['_JAVAHEAPCLASSSTATS_SAMPLE']._serialized_start=560
  _globals['_JAVAHEAPCLASSSTATS_SAMPLE']._serialized_end=647
  _globals['_JAVAHEAPCLASSSTATS_INSTANCESTATS']._serialized_start=650
  _globals['_JAVAHEAPCLASSSTATS_INSTANCESTATS']._serialized_end=798
# @@protoc_insertion_point(module_scope)
