# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/java_heap_histogram.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/java_heap_histogram.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import process_metadata_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_process__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9protos/perfetto/metrics/android/java_heap_histogram.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/metrics/android/process_metadata.proto\"\x94\x04\n\x11JavaHeapHistogram\x12H\n\x0einstance_stats\x18\x01 \x03(\x0b\x32\x30.perfetto.protos.JavaHeapHistogram.InstanceStats\x1a\xc6\x01\n\tTypeCount\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x11\n\tobj_count\x18\x02 \x01(\r\x12\x1b\n\x13reachable_obj_count\x18\x03 \x01(\r\x12\x0f\n\x07size_kb\x18\x05 \x01(\r\x12\x19\n\x11reachable_size_kb\x18\x06 \x01(\r\x12\x16\n\x0enative_size_kb\x18\x07 \x01(\r\x12 \n\x18reachable_native_size_kb\x18\x08 \x01(\r\x1aV\n\x06Sample\x12\n\n\x02ts\x18\x01 \x01(\x03\x12@\n\ntype_count\x18\x02 \x03(\x0b\x32,.perfetto.protos.JavaHeapHistogram.TypeCount\x1a\x93\x01\n\rInstanceStats\x12\x0c\n\x04upid\x18\x01 \x01(\r\x12\x38\n\x07process\x18\x02 \x01(\x0b\x32\'.perfetto.protos.AndroidProcessMetadata\x12:\n\x07samples\x18\x03 \x03(\x0b\x32).perfetto.protos.JavaHeapHistogram.Sample')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.java_heap_histogram_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JAVAHEAPHISTOGRAM']._serialized_start=135
  _globals['_JAVAHEAPHISTOGRAM']._serialized_end=667
  _globals['_JAVAHEAPHISTOGRAM_TYPECOUNT']._serialized_start=231
  _globals['_JAVAHEAPHISTOGRAM_TYPECOUNT']._serialized_end=429
  _globals['_JAVAHEAPHISTOGRAM_SAMPLE']._serialized_start=431
  _globals['_JAVAHEAPHISTOGRAM_SAMPLE']._serialized_end=517
  _globals['_JAVAHEAPHISTOGRAM_INSTANCESTATS']._serialized_start=520
  _globals['_JAVAHEAPHISTOGRAM_INSTANCESTATS']._serialized_end=667
# @@protoc_insertion_point(module_scope)
