# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/java_heap_stats.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/java_heap_stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import process_metadata_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_process__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5protos/perfetto/metrics/android/java_heap_stats.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/metrics/android/process_metadata.proto\"\xed\x04\n\rJavaHeapStats\x12\x44\n\x0einstance_stats\x18\x01 \x03(\x0b\x32,.perfetto.protos.JavaHeapStats.InstanceStats\x1a\x44\n\tHeapRoots\x12\x11\n\troot_type\x18\x01 \x01(\t\x12\x11\n\ttype_name\x18\x02 \x01(\t\x12\x11\n\tobj_count\x18\x03 \x01(\x03\x1a\xbd\x02\n\x06Sample\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x11\n\theap_size\x18\x02 \x01(\x03\x12\x18\n\x10heap_native_size\x18\x08 \x01(\x03\x12\x11\n\tobj_count\x18\x04 \x01(\x03\x12\x1b\n\x13reachable_heap_size\x18\x03 \x01(\x03\x12\"\n\x1areachable_heap_native_size\x18\t \x01(\x03\x12\x1b\n\x13reachable_obj_count\x18\x05 \x01(\x03\x12\x1e\n\x16\x61non_rss_and_swap_size\x18\x06 \x01(\x03\x12\x37\n\x05roots\x18\x07 \x03(\x0b\x32(.perfetto.protos.JavaHeapStats.HeapRoots\x12\x15\n\room_score_adj\x18\n \x01(\x03\x12\x19\n\x11process_uptime_ms\x18\x0b \x01(\x03\x1a\x8f\x01\n\rInstanceStats\x12\x0c\n\x04upid\x18\x01 \x01(\r\x12\x38\n\x07process\x18\x02 \x01(\x0b\x32\'.perfetto.protos.AndroidProcessMetadata\x12\x36\n\x07samples\x18\x03 \x03(\x0b\x32%.perfetto.protos.JavaHeapStats.Sample')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.java_heap_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JAVAHEAPSTATS']._serialized_start=131
  _globals['_JAVAHEAPSTATS']._serialized_end=752
  _globals['_JAVAHEAPSTATS_HEAPROOTS']._serialized_start=218
  _globals['_JAVAHEAPSTATS_HEAPROOTS']._serialized_end=286
  _globals['_JAVAHEAPSTATS_SAMPLE']._serialized_start=289
  _globals['_JAVAHEAPSTATS_SAMPLE']._serialized_end=606
  _globals['_JAVAHEAPSTATS_INSTANCESTATS']._serialized_start=609
  _globals['_JAVAHEAPSTATS_INSTANCESTATS']._serialized_end=752
# @@protoc_insertion_point(module_scope)
