# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/lmk_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/lmk_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protos/perfetto/metrics/android/lmk_metric.proto\x12\x0fperfetto.protos\"\xb9\x01\n\x10\x41ndroidLmkMetric\x12\x13\n\x0btotal_count\x18\x01 \x01(\x05\x12\x42\n\x0c\x62y_oom_score\x18\x02 \x03(\x0b\x32,.perfetto.protos.AndroidLmkMetric.ByOomScore\x12\x18\n\x10oom_victim_count\x18\x03 \x01(\x05\x1a\x32\n\nByOomScore\x12\x15\n\room_score_adj\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.lmk_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDLMKMETRIC']._serialized_start=70
  _globals['_ANDROIDLMKMETRIC']._serialized_end=255
  _globals['_ANDROIDLMKMETRIC_BYOOMSCORE']._serialized_start=205
  _globals['_ANDROIDLMKMETRIC_BYOOMSCORE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
