# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/lmk_reason_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/lmk_reason_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import process_metadata_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_process__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7protos/perfetto/metrics/android/lmk_reason_metric.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/metrics/android/process_metadata.proto\"\xb5\x03\n\x16\x41ndroidLmkReasonMetric\x12\x39\n\x04lmks\x18\x01 \x03(\x0b\x32+.perfetto.protos.AndroidLmkReasonMetric.Lmk\x1a\xc5\x01\n\x07Process\x12\x38\n\x07process\x18\x01 \x01(\x0b\x32\'.perfetto.protos.AndroidProcessMetadata\x12\x15\n\room_score_adj\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12\x16\n\x0e\x66ile_rss_bytes\x18\x04 \x01(\x03\x12\x16\n\x0e\x61non_rss_bytes\x18\x05 \x01(\x03\x12\x17\n\x0fshmem_rss_bytes\x18\x06 \x01(\x03\x12\x12\n\nswap_bytes\x18\x07 \x01(\x03\x1a\x97\x01\n\x03Lmk\x12\x15\n\room_score_adj\x18\x01 \x01(\x05\x12\x17\n\x0fion_heaps_bytes\x18\x04 \x01(\x03\x12\x1c\n\x14system_ion_heap_size\x18\x02 \x01(\x03\x12\x42\n\tprocesses\x18\x03 \x03(\x0b\x32/.perfetto.protos.AndroidLmkReasonMetric.Process')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.lmk_reason_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDLMKREASONMETRIC']._serialized_start=133
  _globals['_ANDROIDLMKREASONMETRIC']._serialized_end=570
  _globals['_ANDROIDLMKREASONMETRIC_PROCESS']._serialized_start=219
  _globals['_ANDROIDLMKREASONMETRIC_PROCESS']._serialized_end=416
  _globals['_ANDROIDLMKREASONMETRIC_LMK']._serialized_start=419
  _globals['_ANDROIDLMKREASONMETRIC_LMK']._serialized_end=570
# @@protoc_insertion_point(module_scope)
