# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/mem_unagg_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/mem_unagg_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6protos/perfetto/metrics/android/mem_unagg_metric.proto\x12\x0fperfetto.protos\"\xf2\x04\n\x1f\x41ndroidMemoryUnaggregatedMetric\x12V\n\x0eprocess_values\x18\x01 \x03(\x0b\x32>.perfetto.protos.AndroidMemoryUnaggregatedMetric.ProcessValues\x1a\x7f\n\rProcessValues\x12\x14\n\x0cprocess_name\x18\x01 \x01(\t\x12X\n\nmem_values\x18\x02 \x01(\x0b\x32\x44.perfetto.protos.AndroidMemoryUnaggregatedMetric.ProcessMemoryValues\x1a\xbe\x02\n\x13ProcessMemoryValues\x12H\n\x08\x61non_rss\x18\x01 \x03(\x0b\x32\x36.perfetto.protos.AndroidMemoryUnaggregatedMetric.Value\x12H\n\x08\x66ile_rss\x18\x02 \x03(\x0b\x32\x36.perfetto.protos.AndroidMemoryUnaggregatedMetric.Value\x12\x44\n\x04swap\x18\x03 \x03(\x0b\x32\x36.perfetto.protos.AndroidMemoryUnaggregatedMetric.Value\x12M\n\ranon_and_swap\x18\x04 \x03(\x0b\x32\x36.perfetto.protos.AndroidMemoryUnaggregatedMetric.Value\x1a\x35\n\x05Value\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x11\n\toom_score\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.mem_unagg_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDMEMORYUNAGGREGATEDMETRIC']._serialized_start=76
  _globals['_ANDROIDMEMORYUNAGGREGATEDMETRIC']._serialized_end=702
  _globals['_ANDROIDMEMORYUNAGGREGATEDMETRIC_PROCESSVALUES']._serialized_start=199
  _globals['_ANDROIDMEMORYUNAGGREGATEDMETRIC_PROCESSVALUES']._serialized_end=326
  _globals['_ANDROIDMEMORYUNAGGREGATEDMETRIC_PROCESSMEMORYVALUES']._serialized_start=329
  _globals['_ANDROIDMEMORYUNAGGREGATEDMETRIC_PROCESSMEMORYVALUES']._serialized_end=647
  _globals['_ANDROIDMEMORYUNAGGREGATEDMETRIC_VALUE']._serialized_start=649
  _globals['_ANDROIDMEMORYUNAGGREGATEDMETRIC_VALUE']._serialized_end=702
# @@protoc_insertion_point(module_scope)
