# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/multiuser_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/multiuser_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6protos/perfetto/metrics/android/multiuser_metric.proto\x12\x0fperfetto.protos\"\xc6\x02\n\x16\x41ndroidMultiuserMetric\x12\x46\n\x0buser_switch\x18\x01 \x01(\x0b\x32\x31.perfetto.protos.AndroidMultiuserMetric.EventData\x1a\xe3\x01\n\tEventData\x12\x13\n\x0b\x64uration_ms\x18\x01 \x01(\x05\x12M\n\tcpu_usage\x18\x02 \x03(\x0b\x32:.perfetto.protos.AndroidMultiuserMetric.EventData.CpuUsage\x1ar\n\x08\x43puUsage\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x14\n\x0cprocess_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63pu_mcycles\x18\x03 \x01(\x05\x12\x16\n\x0e\x63pu_percentage\x18\x04 \x01(\x02\x12\x12\n\nidentifier\x18\x05 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.multiuser_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDMULTIUSERMETRIC']._serialized_start=76
  _globals['_ANDROIDMULTIUSERMETRIC']._serialized_end=402
  _globals['_ANDROIDMULTIUSERMETRIC_EVENTDATA']._serialized_start=175
  _globals['_ANDROIDMULTIUSERMETRIC_EVENTDATA']._serialized_end=402
  _globals['_ANDROIDMULTIUSERMETRIC_EVENTDATA_CPUUSAGE']._serialized_start=288
  _globals['_ANDROIDMULTIUSERMETRIC_EVENTDATA_CPUUSAGE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
