# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/process_metadata.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/process_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6protos/perfetto/metrics/android/process_metadata.proto\x12\x0fperfetto.protos\"\xef\x01\n\x16\x41ndroidProcessMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\x03\x12@\n\x07package\x18\x07 \x01(\x0b\x32/.perfetto.protos.AndroidProcessMetadata.Package\x12\x0b\n\x03pid\x18\t \x01(\x03\x1aM\n\x07Package\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x18\n\x10\x61pk_version_code\x18\x02 \x01(\x03\x12\x12\n\ndebuggable\x18\x03 \x01(\x08J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x08\x10\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.process_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDPROCESSMETADATA']._serialized_start=76
  _globals['_ANDROIDPROCESSMETADATA']._serialized_end=315
  _globals['_ANDROIDPROCESSMETADATA_PACKAGE']._serialized_start=208
  _globals['_ANDROIDPROCESSMETADATA_PACKAGE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
