# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/simpleperf.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/simpleperf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protos/perfetto/metrics/android/simpleperf.proto\x12\x0fperfetto.protos\"\xc8\x03\n\x17\x41ndroidSimpleperfMetric\x12\x14\n\x0curgent_ratio\x18\x01 \x01(\x01\x12H\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x38.perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric\x1a\xcc\x02\n\x0fPerfEventMetric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12S\n\tprocesses\x18\x02 \x03(\x0b\x32@.perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric.Process\x12\r\n\x05total\x18\x03 \x01(\x01\x1a?\n\x06Thread\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x63pu\x18\x03 \x01(\x05\x12\r\n\x05total\x18\x04 \x01(\x01\x1a\x85\x01\n\x07Process\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12P\n\x07threads\x18\x03 \x03(\x0b\x32?.perfetto.protos.AndroidSimpleperfMetric.PerfEventMetric.Thread\x12\r\n\x05total\x18\x04 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.simpleperf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDSIMPLEPERFMETRIC']._serialized_start=70
  _globals['_ANDROIDSIMPLEPERFMETRIC']._serialized_end=526
  _globals['_ANDROIDSIMPLEPERFMETRIC_PERFEVENTMETRIC']._serialized_start=194
  _globals['_ANDROIDSIMPLEPERFMETRIC_PERFEVENTMETRIC']._serialized_end=526
  _globals['_ANDROIDSIMPLEPERFMETRIC_PERFEVENTMETRIC_THREAD']._serialized_start=327
  _globals['_ANDROIDSIMPLEPERFMETRIC_PERFEVENTMETRIC_THREAD']._serialized_end=390
  _globals['_ANDROIDSIMPLEPERFMETRIC_PERFEVENTMETRIC_PROCESS']._serialized_start=393
  _globals['_ANDROIDSIMPLEPERFMETRIC_PERFEVENTMETRIC_PROCESS']._serialized_end=526
# @@protoc_insertion_point(module_scope)
