# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/surfaceflinger.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/surfaceflinger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4protos/perfetto/metrics/android/surfaceflinger.proto\x12\x0fperfetto.protos\"\xd5\x04\n\x1b\x41ndroidSurfaceflingerMetric\x12\x15\n\rmissed_frames\x18\x01 \x01(\r\x12\x19\n\x11missed_hwc_frames\x18\x02 \x01(\r\x12\x19\n\x11missed_gpu_frames\x18\x03 \x01(\r\x12\x19\n\x11missed_frame_rate\x18\x04 \x01(\x01\x12\x1d\n\x15missed_hwc_frame_rate\x18\x05 \x01(\x01\x12\x1d\n\x15missed_gpu_frame_rate\x18\x06 \x01(\x01\x12\x17\n\x0fgpu_invocations\x18\x07 \x01(\r\x12\x1e\n\x16\x61vg_gpu_waiting_dur_ms\x18\x08 \x01(\x01\x12*\n\"total_non_empty_gpu_waiting_dur_ms\x18\t \x01(\x01\x12[\n\x13metrics_per_display\x18\n \x03(\x0b\x32>.perfetto.protos.AndroidSurfaceflingerMetric.MetricsPerDisplay\x1a\xcd\x01\n\x11MetricsPerDisplay\x12\x12\n\ndisplay_id\x18\x01 \x01(\t\x12\x15\n\rmissed_frames\x18\x02 \x01(\r\x12\x19\n\x11missed_hwc_frames\x18\x03 \x01(\r\x12\x19\n\x11missed_gpu_frames\x18\x04 \x01(\r\x12\x19\n\x11missed_frame_rate\x18\x05 \x01(\x01\x12\x1d\n\x15missed_hwc_frame_rate\x18\x06 \x01(\x01\x12\x1d\n\x15missed_gpu_frame_rate\x18\x07 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.surfaceflinger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDSURFACEFLINGERMETRIC']._serialized_start=74
  _globals['_ANDROIDSURFACEFLINGERMETRIC']._serialized_end=671
  _globals['_ANDROIDSURFACEFLINGERMETRIC_METRICSPERDISPLAY']._serialized_start=466
  _globals['_ANDROIDSURFACEFLINGERMETRIC_METRICSPERDISPLAY']._serialized_end=671
# @@protoc_insertion_point(module_scope)
