# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/sysui_slice_performance_statistical_data.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/sysui_slice_performance_statistical_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNprotos/perfetto/metrics/android/sysui_slice_performance_statistical_data.proto\x12\x0fperfetto.protos\"\x91\x01\n$SysUiSlicePerformanceStatisticalData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x63nt\x18\x02 \x01(\x03\x12\x12\n\navg_dur_ms\x18\x03 \x01(\x03\x12\x12\n\nmax_dur_ms\x18\x04 \x01(\x03\x12\x12\n\navg_dur_ns\x18\x06 \x01(\x03\x12\x12\n\nmax_dur_ns\x18\x07 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.sysui_slice_performance_statistical_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSUISLICEPERFORMANCESTATISTICALDATA']._serialized_start=100
  _globals['_SYSUISLICEPERFORMANCESTATISTICALDATA']._serialized_end=245
# @@protoc_insertion_point(module_scope)
