# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/sysui_update_notif_on_ui_mode_changed_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/sysui_update_notif_on_ui_mode_changed_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import sysui_slice_performance_statistical_data_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_sysui__slice__performance__statistical__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRprotos/perfetto/metrics/android/sysui_update_notif_on_ui_mode_changed_metric.proto\x12\x0fperfetto.protos\x1aNprotos/perfetto/metrics/android/sysui_slice_performance_statistical_data.proto\"\x92\x02\n%SysuiUpdateNotifOnUiModeChangedMetric\x12U\n\x16\x61ll_slices_performance\x18\x01 \x01(\x0b\x32\x35.perfetto.protos.SysUiSlicePerformanceStatisticalData\x12S\n\x05slice\x18\x02 \x03(\x0b\x32\x44.perfetto.protos.SysuiUpdateNotifOnUiModeChangedMetric.SliceDuration\x1a=\n\rSliceDuration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x64ur_ms\x18\x02 \x01(\x03\x12\x0e\n\x06\x64ur_ns\x18\x03 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.sysui_update_notif_on_ui_mode_changed_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSUIUPDATENOTIFONUIMODECHANGEDMETRIC']._serialized_start=184
  _globals['_SYSUIUPDATENOTIFONUIMODECHANGEDMETRIC']._serialized_end=458
  _globals['_SYSUIUPDATENOTIFONUIMODECHANGEDMETRIC_SLICEDURATION']._serialized_start=397
  _globals['_SYSUIUPDATENOTIFONUIMODECHANGEDMETRIC_SLICEDURATION']._serialized_end=458
# @@protoc_insertion_point(module_scope)
