# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/thread_time_in_state_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/thread_time_in_state_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics.android import process_metadata_pb2 as protos_dot_perfetto_dot_metrics_dot_android_dot_process__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAprotos/perfetto/metrics/android/thread_time_in_state_metric.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/metrics/android/process_metadata.proto\"\xf0\x04\n\x1e\x41ndroidThreadTimeInStateMetric\x12J\n\tprocesses\x18\x01 \x03(\x0b\x32\x37.perfetto.protos.AndroidThreadTimeInStateMetric.Process\x1a\x81\x01\n\x11MetricsByCoreType\x12\x19\n\x11time_in_state_cpu\x18\x05 \x01(\x05\x12\x11\n\tcore_type\x18\x01 \x01(\t\x12\x12\n\nruntime_ms\x18\x02 \x01(\x03\x12\x0f\n\x07mcycles\x18\x03 \x01(\x03\x12\x19\n\x11power_profile_mah\x18\x04 \x01(\x01\x1a\x8c\x01\n\x06Thread\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bmain_thread\x18\x03 \x01(\x08\x12_\n\x14metrics_by_core_type\x18\x02 \x03(\x0b\x32\x41.perfetto.protos.AndroidThreadTimeInStateMetric.MetricsByCoreType\x1a\xee\x01\n\x07Process\x12\x39\n\x08metadata\x18\x01 \x01(\x0b\x32\'.perfetto.protos.AndroidProcessMetadata\x12_\n\x14metrics_by_core_type\x18\x02 \x03(\x0b\x32\x41.perfetto.protos.AndroidThreadTimeInStateMetric.MetricsByCoreType\x12G\n\x07threads\x18\x03 \x03(\x0b\x32\x36.perfetto.protos.AndroidThreadTimeInStateMetric.Thread')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.thread_time_in_state_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDTHREADTIMEINSTATEMETRIC']._serialized_start=143
  _globals['_ANDROIDTHREADTIMEINSTATEMETRIC']._serialized_end=767
  _globals['_ANDROIDTHREADTIMEINSTATEMETRIC_METRICSBYCORETYPE']._serialized_start=254
  _globals['_ANDROIDTHREADTIMEINSTATEMETRIC_METRICSBYCORETYPE']._serialized_end=383
  _globals['_ANDROIDTHREADTIMEINSTATEMETRIC_THREAD']._serialized_start=386
  _globals['_ANDROIDTHREADTIMEINSTATEMETRIC_THREAD']._serialized_end=526
  _globals['_ANDROIDTHREADTIMEINSTATEMETRIC_PROCESS']._serialized_start=529
  _globals['_ANDROIDTHREADTIMEINSTATEMETRIC_PROCESS']._serialized_end=767
# @@protoc_insertion_point(module_scope)
