# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/android/trace_quality.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/android/trace_quality.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3protos/perfetto/metrics/android/trace_quality.proto\x12\x0fperfetto.protos\"z\n\x19\x41ndroidTraceQualityMetric\x12\x44\n\x08\x66\x61ilures\x18\x01 \x03(\x0b\x32\x32.perfetto.protos.AndroidTraceQualityMetric.Failure\x1a\x17\n\x07\x46\x61ilure\x12\x0c\n\x04name\x18\x01 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.android.trace_quality_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDTRACEQUALITYMETRIC']._serialized_start=72
  _globals['_ANDROIDTRACEQUALITYMETRIC']._serialized_end=194
  _globals['_ANDROIDTRACEQUALITYMETRIC_FAILURE']._serialized_start=171
  _globals['_ANDROIDTRACEQUALITYMETRIC_FAILURE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
