# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/view/inputmethod/inputmethodmanager.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/view/inputmethod/inputmethodmanager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGprotos/perfetto/trace/android/view/inputmethod/inputmethodmanager.proto\x12\x0fperfetto.protos\"\xb0\x01\n\x17InputMethodManagerProto\x12\x0e\n\x06\x63ur_id\x18\x01 \x01(\t\x12\x17\n\x0f\x66ullscreen_mode\x18\x02 \x01(\x08\x12\x12\n\ndisplay_id\x18\x03 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12\x19\n\x11served_connecting\x18\x05 \x01(\x08\x12\x13\n\x0bserved_view\x18\x06 \x01(\t\x12\x18\n\x10next_served_view\x18\x07 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.view.inputmethod.inputmethodmanager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTMETHODMANAGERPROTO']._serialized_start=93
  _globals['_INPUTMETHODMANAGERPROTO']._serialized_end=269
# @@protoc_insertion_point(module_scope)
