# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/server/animationadapter.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/server/animationadapter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.graphics import point_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_graphics_dot_point__pb2
from protos.perfetto.trace.android.view import remote_animation_target_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_view_dot_remote__animation__target__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;protos/perfetto/trace/android/server/animationadapter.proto\x12\x0fperfetto.protos\x1a\x32protos/perfetto/trace/android/graphics/point.proto\x1a@protos/perfetto/trace/android/view/remote_animation_target.proto\"\x98\x01\n\x15\x41nimationAdapterProto\x12:\n\x05local\x18\x01 \x01(\x0b\x32+.perfetto.protos.LocalAnimationAdapterProto\x12\x43\n\x06remote\x18\x02 \x01(\x0b\x32\x33.perfetto.protos.RemoteAnimationAdapterWrapperProto\"a\n\"RemoteAnimationAdapterWrapperProto\x12;\n\x06target\x18\x01 \x01(\x0b\x32+.perfetto.protos.RemoteAnimationTargetProto\"Y\n\x1aLocalAnimationAdapterProto\x12;\n\x0e\x61nimation_spec\x18\x01 \x01(\x0b\x32#.perfetto.protos.AnimationSpecProto\"\xfc\x01\n\x12\x41nimationSpecProto\x12\x39\n\x06window\x18\x01 \x01(\x0b\x32).perfetto.protos.WindowAnimationSpecProto\x12\x35\n\x04move\x18\x02 \x01(\x0b\x32\'.perfetto.protos.MoveAnimationSpecProto\x12\x37\n\x05\x61lpha\x18\x03 \x01(\x0b\x32(.perfetto.protos.AlphaAnimationSpecProto\x12;\n\x06rotate\x18\x04 \x01(\x0b\x32+.perfetto.protos.RotationAnimationSpecProto\"-\n\x18WindowAnimationSpecProto\x12\x11\n\tanimation\x18\x01 \x01(\t\"\x81\x01\n\x16MoveAnimationSpecProto\x12)\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x1b.perfetto.protos.PointProto\x12\'\n\x02to\x18\x02 \x01(\x0b\x32\x1b.perfetto.protos.PointProto\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03\"H\n\x17\x41lphaAnimationSpecProto\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x02\x12\n\n\x02to\x18\x02 \x01(\x02\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03\"W\n\x1aRotationAnimationSpecProto\x12\x12\n\nstart_luma\x18\x01 \x01(\x02\x12\x10\n\x08\x65nd_luma\x18\x02 \x01(\x02\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.server.animationadapter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANIMATIONADAPTERPROTO']._serialized_start=199
  _globals['_ANIMATIONADAPTERPROTO']._serialized_end=351
  _globals['_REMOTEANIMATIONADAPTERWRAPPERPROTO']._serialized_start=353
  _globals['_REMOTEANIMATIONADAPTERWRAPPERPROTO']._serialized_end=450
  _globals['_LOCALANIMATIONADAPTERPROTO']._serialized_start=452
  _globals['_LOCALANIMATIONADAPTERPROTO']._serialized_end=541
  _globals['_ANIMATIONSPECPROTO']._serialized_start=544
  _globals['_ANIMATIONSPECPROTO']._serialized_end=796
  _globals['_WINDOWANIMATIONSPECPROTO']._serialized_start=798
  _globals['_WINDOWANIMATIONSPECPROTO']._serialized_end=843
  _globals['_MOVEANIMATIONSPECPROTO']._serialized_start=846
  _globals['_MOVEANIMATIONSPECPROTO']._serialized_end=975
  _globals['_ALPHAANIMATIONSPECPROTO']._serialized_start=977
  _globals['_ALPHAANIMATIONSPECPROTO']._serialized_end=1049
  _globals['_ROTATIONANIMATIONSPECPROTO']._serialized_start=1051
  _globals['_ROTATIONANIMATIONSPECPROTO']._serialized_end=1138
# @@protoc_insertion_point(module_scope)
