# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/server/surfaceanimator.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/server/surfaceanimator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.server import animationadapter_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_server_dot_animationadapter__pb2
from protos.perfetto.trace.android.view import surfacecontrol_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_view_dot_surfacecontrol__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:protos/perfetto/trace/android/server/surfaceanimator.proto\x12\x0fperfetto.protos\x1a;protos/perfetto/trace/android/server/animationadapter.proto\x1a\x37protos/perfetto/trace/android/view/surfacecontrol.proto\"\xaf\x01\n\x14SurfaceAnimatorProto\x12\x33\n\x05leash\x18\x01 \x01(\x0b\x32$.perfetto.protos.SurfaceControlProto\x12\x1f\n\x17\x61nimation_start_delayed\x18\x02 \x01(\x08\x12\x41\n\x11\x61nimation_adapter\x18\x03 \x01(\x0b\x32&.perfetto.protos.AnimationAdapterProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.server.surfaceanimator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SURFACEANIMATORPROTO']._serialized_start=198
  _globals['_SURFACEANIMATORPROTO']._serialized_end=373
# @@protoc_insertion_point(module_scope)
