# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/server/windowcontainerthumbnail.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/server/windowcontainerthumbnail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.server import surfaceanimator_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_server_dot_surfaceanimator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCprotos/perfetto/trace/android/server/windowcontainerthumbnail.proto\x12\x0fperfetto.protos\x1a:protos/perfetto/trace/android/server/surfaceanimator.proto\"\x7f\n\x1dWindowContainerThumbnailProto\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12?\n\x10surface_animator\x18\x03 \x01(\x0b\x32%.perfetto.protos.SurfaceAnimatorProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.server.windowcontainerthumbnail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WINDOWCONTAINERTHUMBNAILPROTO']._serialized_start=148
  _globals['_WINDOWCONTAINERTHUMBNAILPROTO']._serialized_end=275
# @@protoc_insertion_point(module_scope)
