# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/viewcapture.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/viewcapture.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/protos/perfetto/trace/android/viewcapture.proto\x12\x0fperfetto.protos\"\xeb\x03\n\x0bViewCapture\x12\x18\n\x10package_name_iid\x18\x01 \x01(\x05\x12\x17\n\x0fwindow_name_iid\x18\x02 \x01(\x05\x12\x30\n\x05views\x18\x03 \x03(\x0b\x32!.perfetto.protos.ViewCapture.View\x1a\xf6\x02\n\x04View\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tparent_id\x18\x02 \x01(\x05\x12\x10\n\x08hashcode\x18\x03 \x01(\x05\x12\x13\n\x0bview_id_iid\x18\x04 \x01(\x05\x12\x16\n\x0e\x63lass_name_iid\x18\x05 \x01(\x05\x12\x0c\n\x04left\x18\x06 \x01(\x05\x12\x0b\n\x03top\x18\x07 \x01(\x05\x12\r\n\x05width\x18\x08 \x01(\x05\x12\x0e\n\x06height\x18\t \x01(\x05\x12\x10\n\x08scroll_x\x18\n \x01(\x05\x12\x10\n\x08scroll_y\x18\x0b \x01(\x05\x12\x15\n\rtranslation_x\x18\x0c \x01(\x02\x12\x15\n\rtranslation_y\x18\r \x01(\x02\x12\x0f\n\x07scale_x\x18\x0e \x01(\x02\x12\x0f\n\x07scale_y\x18\x0f \x01(\x02\x12\r\n\x05\x61lpha\x18\x10 \x01(\x02\x12\x15\n\rwill_not_draw\x18\x11 \x01(\x08\x12\x15\n\rclip_children\x18\x12 \x01(\x08\x12\x12\n\nvisibility\x18\x13 \x01(\x05\x12\x11\n\televation\x18\x14 \x01(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.viewcapture_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIEWCAPTURE']._serialized_start=69
  _globals['_VIEWCAPTURE']._serialized_end=560
  _globals['_VIEWCAPTURE_VIEW']._serialized_start=186
  _globals['_VIEWCAPTURE_VIEW']._serialized_end=560
# @@protoc_insertion_point(module_scope)
