# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/windowmanager.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/windowmanager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.server import windowmanagerservice_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_server_dot_windowmanagerservice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1protos/perfetto/trace/android/windowmanager.proto\x12\x0fperfetto.protos\x1a?protos/perfetto/trace/android/server/windowmanagerservice.proto\"\xe3\x01\n\x1bWindowManagerTraceFileProto\x12\x14\n\x0cmagic_number\x18\x01 \x01(\x06\x12\x37\n\x05\x65ntry\x18\x02 \x03(\x0b\x32(.perfetto.protos.WindowManagerTraceEntry\x12)\n!real_to_elapsed_time_offset_nanos\x18\x03 \x01(\x06\"J\n\x0bMagicNumber\x12\x0b\n\x07INVALID\x10\x00\x12\x16\n\x0eMAGIC_NUMBER_L\x10\xd7\x92\xb9\xa2\x05\x12\x16\n\x0eMAGIC_NUMBER_H\x10\xd2\x82\x8d\xaa\x04\"\x98\x01\n\x17WindowManagerTraceEntry\x12\x1e\n\x16\x65lapsed_realtime_nanos\x18\x01 \x01(\x06\x12\r\n\x05where\x18\x02 \x01(\t\x12N\n\x16window_manager_service\x18\x03 \x01(\x0b\x32..perfetto.protos.WindowManagerServiceDumpProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.windowmanager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WINDOWMANAGERTRACEFILEPROTO']._serialized_start=136
  _globals['_WINDOWMANAGERTRACEFILEPROTO']._serialized_end=363
  _globals['_WINDOWMANAGERTRACEFILEPROTO_MAGICNUMBER']._serialized_start=289
  _globals['_WINDOWMANAGERTRACEFILEPROTO_MAGICNUMBER']._serialized_end=363
  _globals['_WINDOWMANAGERTRACEENTRY']._serialized_start=366
  _globals['_WINDOWMANAGERTRACEENTRY']._serialized_end=518
# @@protoc_insertion_point(module_scope)
