# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/view/displayinfo.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/view/displayinfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.view import displaycutout_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_view_dot_displaycutout__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4protos/perfetto/trace/android/view/displayinfo.proto\x12\x0fperfetto.protos\x1a\x36protos/perfetto/trace/android/view/displaycutout.proto\"\xba\x01\n\x10\x44isplayInfoProto\x12\x15\n\rlogical_width\x18\x01 \x01(\x05\x12\x16\n\x0elogical_height\x18\x02 \x01(\x05\x12\x11\n\tapp_width\x18\x03 \x01(\x05\x12\x12\n\napp_height\x18\x04 \x01(\x05\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\r\n\x05\x66lags\x18\x06 \x01(\x05\x12\x33\n\x06\x63utout\x18\x07 \x01(\x0b\x32#.perfetto.protos.DisplayCutoutProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.view.displayinfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISPLAYINFOPROTO']._serialized_start=130
  _globals['_DISPLAYINFOPROTO']._serialized_end=316
# @@protoc_insertion_point(module_scope)
