# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/view/displaycutout.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/view/displaycutout.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.graphics import rect_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_graphics_dot_rect__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6protos/perfetto/trace/android/view/displaycutout.proto\x12\x0fperfetto.protos\x1a\x31protos/perfetto/trace/android/graphics/rect.proto\"\xd6\x02\n\x12\x44isplayCutoutProto\x12*\n\x06insets\x18\x01 \x01(\x0b\x32\x1a.perfetto.protos.RectProto\x12.\n\nbound_left\x18\x03 \x01(\x0b\x32\x1a.perfetto.protos.RectProto\x12-\n\tbound_top\x18\x04 \x01(\x0b\x32\x1a.perfetto.protos.RectProto\x12/\n\x0b\x62ound_right\x18\x05 \x01(\x0b\x32\x1a.perfetto.protos.RectProto\x12\x30\n\x0c\x62ound_bottom\x18\x06 \x01(\x0b\x32\x1a.perfetto.protos.RectProto\x12\x34\n\x10waterfall_insets\x18\x07 \x01(\x0b\x32\x1a.perfetto.protos.RectProto\x12\x16\n\x0eside_overrides\x18\x08 \x03(\x05J\x04\x08\x02\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.view.displaycutout_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISPLAYCUTOUTPROTO']._serialized_start=127
  _globals['_DISPLAYCUTOUTPROTO']._serialized_end=469
# @@protoc_insertion_point(module_scope)
