# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/view/imefocuscontroller.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/view/imefocuscontroller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;protos/perfetto/trace/android/view/imefocuscontroller.proto\x12\x0fperfetto.protos\"g\n\x17ImeFocusControllerProto\x12\x15\n\rhas_ime_focus\x18\x01 \x01(\x08\x12\x17\n\x0bserved_view\x18\x02 \x01(\tB\x02\x18\x01\x12\x1c\n\x10next_served_view\x18\x03 \x01(\tB\x02\x18\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.view.imefocuscontroller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMEFOCUSCONTROLLERPROTO'].fields_by_name['served_view']._loaded_options = None
  _globals['_IMEFOCUSCONTROLLERPROTO'].fields_by_name['served_view']._serialized_options = b'\030\001'
  _globals['_IMEFOCUSCONTROLLERPROTO'].fields_by_name['next_served_view']._loaded_options = None
  _globals['_IMEFOCUSCONTROLLERPROTO'].fields_by_name['next_served_view']._serialized_options = b'\030\001'
  _globals['_IMEFOCUSCONTROLLERPROTO']._serialized_start=80
  _globals['_IMEFOCUSCONTROLLERPROTO']._serialized_end=183
# @@protoc_insertion_point(module_scope)
