# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/view/insetssourcecontrol.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/view/insetssourcecontrol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.graphics import point_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_graphics_dot_point__pb2
from protos.perfetto.trace.android.view import surfacecontrol_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_view_dot_surfacecontrol__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<protos/perfetto/trace/android/view/insetssourcecontrol.proto\x12\x0fperfetto.protos\x1a\x32protos/perfetto/trace/android/graphics/point.proto\x1a\x37protos/perfetto/trace/android/view/surfacecontrol.proto\"\xa5\x01\n\x18InsetsSourceControlProto\x12\x10\n\x04type\x18\x01 \x01(\tB\x02\x18\x01\x12-\n\x08position\x18\x02 \x01(\x0b\x32\x1b.perfetto.protos.PointProto\x12\x33\n\x05leash\x18\x03 \x01(\x0b\x32$.perfetto.protos.SurfaceControlProto\x12\x13\n\x0btype_number\x18\x04 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.view.insetssourcecontrol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSETSSOURCECONTROLPROTO'].fields_by_name['type']._loaded_options = None
  _globals['_INSETSSOURCECONTROLPROTO'].fields_by_name['type']._serialized_options = b'\030\001'
  _globals['_INSETSSOURCECONTROLPROTO']._serialized_start=191
  _globals['_INSETSSOURCECONTROLPROTO']._serialized_end=356
# @@protoc_insertion_point(module_scope)
