# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/view/insetscontroller.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/view/insetscontroller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.view import insetsstate_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_view_dot_insetsstate__pb2
from protos.perfetto.trace.android.view import insetsanimationcontrolimpl_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_view_dot_insetsanimationcontrolimpl__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9protos/perfetto/trace/android/view/insetscontroller.proto\x12\x0fperfetto.protos\x1a\x34protos/perfetto/trace/android/view/insetsstate.proto\x1a\x43protos/perfetto/trace/android/view/insetsanimationcontrolimpl.proto\"\x8c\x01\n\x15InsetsControllerProto\x12\x30\n\x05state\x18\x01 \x01(\x0b\x32!.perfetto.protos.InsetsStateProto\x12\x41\n\x07\x63ontrol\x18\x02 \x03(\x0b\x32\x30.perfetto.protos.InsetsAnimationControlImplProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.view.insetscontroller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSETSCONTROLLERPROTO']._serialized_start=202
  _globals['_INSETSCONTROLLERPROTO']._serialized_end=342
# @@protoc_insertion_point(module_scope)
