# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/view/surface.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/view/surface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protos/perfetto/trace/android/view/surface.proto\x12\x0fperfetto.protos\"_\n\x0cSurfaceProto\"O\n\x08Rotation\x12\x0e\n\nROTATION_0\x10\x00\x12\x0f\n\x0bROTATION_90\x10\x01\x12\x10\n\x0cROTATION_180\x10\x02\x12\x10\n\x0cROTATION_270\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.view.surface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SURFACEPROTO']._serialized_start=69
  _globals['_SURFACEPROTO']._serialized_end=164
  _globals['_SURFACEPROTO_ROTATION']._serialized_start=85
  _globals['_SURFACEPROTO_ROTATION']._serialized_end=164
# @@protoc_insertion_point(module_scope)
