# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/bigtrace/worker.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/bigtrace/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace_processor import trace_processor_pb2 as protos_dot_perfetto_dot_trace__processor_dot_trace__processor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%protos/perfetto/bigtrace/worker.proto\x12\x0fperfetto.protos\x1a\x35protos/perfetto/trace_processor/trace_processor.proto\"\\\n\x16\x42igtraceQueryTraceArgs\x12\x12\n\x05trace\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tsql_query\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_traceB\x0c\n\n_sql_query\"h\n\x1a\x42igtraceQueryTraceResponse\x12\x12\n\x05trace\x18\x01 \x01(\tH\x00\x88\x01\x01\x12,\n\x06result\x18\x02 \x03(\x0b\x32\x1c.perfetto.protos.QueryResultB\x08\n\x06_trace2t\n\x0e\x42igtraceWorker\x12\x62\n\nQueryTrace\x12\'.perfetto.protos.BigtraceQueryTraceArgs\x1a+.perfetto.protos.BigtraceQueryTraceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.bigtrace.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIGTRACEQUERYTRACEARGS']._serialized_start=113
  _globals['_BIGTRACEQUERYTRACEARGS']._serialized_end=205
  _globals['_BIGTRACEQUERYTRACERESPONSE']._serialized_start=207
  _globals['_BIGTRACEQUERYTRACERESPONSE']._serialized_end=311
  _globals['_BIGTRACEWORKER']._serialized_start=313
  _globals['_BIGTRACEWORKER']._serialized_end=429
# @@protoc_insertion_point(module_scope)
