# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/test_extensions.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/test_extensions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.track_event import track_event_pb2 as protos_dot_perfetto_dot_trace_dot_track__event_dot_track__event__pb2
from protos.perfetto.trace.track_event import debug_annotation_pb2 as protos_dot_perfetto_dot_trace_dot_track__event_dot_debug__annotation__pb2

from protos.perfetto.trace.track_event.track_event_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+protos/perfetto/trace/test_extensions.proto\x12\x0fperfetto.protos\x1a\x33protos/perfetto/trace/track_event/track_event.proto\x1a\x38protos/perfetto/trace/track_event/debug_annotation.proto\"\xd1\x03\n\rTestExtension2B\n\x1cstring_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xacM \x01(\t2C\n\x1dstring_extension_for_testing2\x12\x1b.perfetto.protos.TrackEvent\x18\xb1M \x01(\t2?\n\x19int_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xadM \x03(\x05\x32\x43\n\x1domitted_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xaeM \x01(\t2o\n$nested_message_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xafM \x01(\x0b\x32#.perfetto.protos.TestExtensionChild2@\n\x1auint_extension_for_testing\x12\x1b.perfetto.protos.TrackEvent\x18\xb0M \x01(\r\"r\n\x12TestExtensionChild\x12\x1f\n\x17\x63hild_field_for_testing\x18\x01 \x01(\t\x12;\n\x11\x64\x65\x62ug_annotations\x18\x63 \x03(\x0b\x32 .perfetto.protos.DebugAnnotationP\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.test_extensions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTEXTENSION']._serialized_start=176
  _globals['_TESTEXTENSION']._serialized_end=641
  _globals['_TESTEXTENSIONCHILD']._serialized_start=643
  _globals['_TESTEXTENSIONCHILD']._serialized_end=757
# @@protoc_insertion_point(module_scope)
