# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/webview/all_webview_metrics.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/webview/all_webview_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics import metrics_pb2 as protos_dot_perfetto_dot_metrics_dot_metrics__pb2
from protos.perfetto.metrics.webview import webview_jank_approximation_pb2 as protos_dot_perfetto_dot_metrics_dot_webview_dot_webview__jank__approximation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9protos/perfetto/metrics/webview/all_webview_metrics.proto\x12\x0fperfetto.protos\x1a%protos/perfetto/metrics/metrics.proto\x1a@protos/perfetto/metrics/webview/webview_jank_approximation.proto:m\n\x1awebview_jank_approximation\x12\x1d.perfetto.protos.TraceMetrics\x18\xd1\x0f \x01(\x0b\x32).perfetto.protos.WebViewJankApproximation')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.webview.all_webview_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
