# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/app/statusbarmanager.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/app/statusbarmanager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8protos/perfetto/trace/android/app/statusbarmanager.proto\x12\x0fperfetto.protos\"\xfa\x01\n\x15StatusBarManagerProto\"Y\n\x0bWindowState\x12\x18\n\x14WINDOW_STATE_SHOWING\x10\x00\x12\x17\n\x13WINDOW_STATE_HIDING\x10\x01\x12\x17\n\x13WINDOW_STATE_HIDDEN\x10\x02\"\x85\x01\n\x14TransientWindowState\x12\x16\n\x12TRANSIENT_BAR_NONE\x10\x00\x12 \n\x1cTRANSIENT_BAR_SHOW_REQUESTED\x10\x01\x12\x19\n\x15TRANSIENT_BAR_SHOWING\x10\x02\x12\x18\n\x14TRANSIENT_BAR_HIDING\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.app.statusbarmanager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSBARMANAGERPROTO']._serialized_start=78
  _globals['_STATUSBARMANAGERPROTO']._serialized_end=328
  _globals['_STATUSBARMANAGERPROTO_WINDOWSTATE']._serialized_start=103
  _globals['_STATUSBARMANAGERPROTO_WINDOWSTATE']._serialized_end=192
  _globals['_STATUSBARMANAGERPROTO_TRANSIENTWINDOWSTATE']._serialized_start=195
  _globals['_STATUSBARMANAGERPROTO_TRANSIENTWINDOWSTATE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
