# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/trace/android/server/inputmethod/inputmethodmanagerservice.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/trace/android/server/inputmethod/inputmethodmanagerservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.trace.android.view.inputmethod import editorinfo_pb2 as protos_dot_perfetto_dot_trace_dot_android_dot_view_dot_inputmethod_dot_editorinfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPprotos/perfetto/trace/android/server/inputmethod/inputmethodmanagerservice.proto\x12\x0fperfetto.protos\x1a?protos/perfetto/trace/android/view/inputmethod/editorinfo.proto\"\xc5\x05\n\x1eInputMethodManagerServiceProto\x12\x15\n\rcur_method_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ur_seq\x18\x02 \x01(\x05\x12\x12\n\ncur_client\x18\x03 \x01(\t\x12\x1f\n\x17\x63ur_focused_window_name\x18\x04 \x01(\t\x12#\n\x1blast_ime_target_window_name\x18\x05 \x01(\t\x12*\n\"cur_focused_window_soft_input_mode\x18\x06 \x01(\t\x12\x37\n\rcur_attribute\x18\x07 \x01(\x0b\x32 .perfetto.protos.EditorInfoProto\x12\x0e\n\x06\x63ur_id\x18\x08 \x01(\t\x12!\n\x19show_explicitly_requested\x18\n \x01(\x08\x12\x13\n\x0bshow_forced\x18\x0b \x01(\x08\x12\x13\n\x0binput_shown\x18\x0c \x01(\x08\x12\x1a\n\x12in_fullscreen_mode\x18\r \x01(\x08\x12\x11\n\tcur_token\x18\x0e \x01(\t\x12\x1c\n\x14\x63ur_token_display_id\x18\x0f \x01(\x05\x12\x14\n\x0csystem_ready\x18\x10 \x01(\x08\x12\x1b\n\x13last_switch_user_id\x18\x11 \x01(\x05\x12\x17\n\x0fhave_connection\x18\x12 \x01(\x08\x12\x17\n\x0f\x62ound_to_method\x18\x13 \x01(\x08\x12\x16\n\x0eis_interactive\x18\x14 \x01(\x08\x12\x18\n\x10\x62\x61\x63k_disposition\x18\x15 \x01(\x05\x12\x1d\n\x15ime_window_visibility\x18\x16 \x01(\x05\x12#\n\x1bshow_ime_with_hard_keyboard\x18\x17 \x01(\x08\x12\x31\n)accessibility_requesting_no_soft_keyboard\x18\x18 \x01(\x08J\x04\x08\t\x10\n')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.trace.android.server.inputmethod.inputmethodmanagerservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTMETHODMANAGERSERVICEPROTO']._serialized_start=167
  _globals['_INPUTMETHODMANAGERSERVICEPROTO']._serialized_end=876
# @@protoc_insertion_point(module_scope)
