# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/chrome/args_class_names.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/chrome/args_class_names.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5protos/perfetto/metrics/chrome/args_class_names.proto\x12\x0fperfetto.protos\"\xdf\x01\n\x14\x43hromeArgsClassNames\x12\x65\n\x17\x63lass_names_per_version\x18\x01 \x03(\x0b\x32\x44.perfetto.protos.ChromeArgsClassNames.ChromeArgsClassNamesPerVersion\x1a`\n\x1e\x43hromeArgsClassNamesPerVersion\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x14\n\x0cversion_code\x18\x02 \x01(\x03\x12\x12\n\nclass_name\x18\x03 \x03(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.chrome.args_class_names_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHROMEARGSCLASSNAMES']._serialized_start=75
  _globals['_CHROMEARGSCLASSNAMES']._serialized_end=298
  _globals['_CHROMEARGSCLASSNAMES_CHROMEARGSCLASSNAMESPERVERSION']._serialized_start=202
  _globals['_CHROMEARGSCLASSNAMES_CHROMEARGSCLASSNAMESPERVERSION']._serialized_end=298
# @@protoc_insertion_point(module_scope)
