# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/chrome/dropped_frames.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/chrome/dropped_frames.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3protos/perfetto/metrics/chrome/dropped_frames.proto\x12\x0fperfetto.protos\"\x9e\x01\n\x13\x43hromeDroppedFrames\x12H\n\rdropped_frame\x18\x01 \x03(\x0b\x32\x31.perfetto.protos.ChromeDroppedFrames.DroppedFrame\x1a=\n\x0c\x44roppedFrame\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x14\n\x0cprocess_name\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.chrome.dropped_frames_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHROMEDROPPEDFRAMES']._serialized_start=73
  _globals['_CHROMEDROPPEDFRAMES']._serialized_end=231
  _globals['_CHROMEDROPPEDFRAMES_DROPPEDFRAME']._serialized_start=170
  _globals['_CHROMEDROPPEDFRAMES_DROPPEDFRAME']._serialized_end=231
# @@protoc_insertion_point(module_scope)
