# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/chrome/frame_times.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/chrome/frame_times.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics import custom_options_pb2 as protos_dot_perfetto_dot_metrics_dot_custom__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0protos/perfetto/metrics/chrome/frame_times.proto\x12\x0fperfetto.protos\x1a,protos/perfetto/metrics/custom_options.proto\"\xd8\x01\n\nFrameTimes\x12*\n\nframe_time\x18\x01 \x03(\x01\x42\x16\x8a\xb5\x18\x12ms_smallerIsBetter\x12.\n\x0e\x65xp_frame_time\x18\x02 \x03(\x01\x42\x16\x8a\xb5\x18\x12ms_smallerIsBetter\x12\x34\n\x0f\x61vg_surface_fps\x18\x03 \x01(\x01\x42\x1b\x8a\xb5\x18\x17unitless_biggerIsBetter\x12\x38\n\x13\x65xp_avg_surface_fps\x18\x04 \x01(\x01\x42\x1b\x8a\xb5\x18\x17unitless_biggerIsBetter')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.chrome.frame_times_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMETIMES'].fields_by_name['frame_time']._loaded_options = None
  _globals['_FRAMETIMES'].fields_by_name['frame_time']._serialized_options = b'\212\265\030\022ms_smallerIsBetter'
  _globals['_FRAMETIMES'].fields_by_name['exp_frame_time']._loaded_options = None
  _globals['_FRAMETIMES'].fields_by_name['exp_frame_time']._serialized_options = b'\212\265\030\022ms_smallerIsBetter'
  _globals['_FRAMETIMES'].fields_by_name['avg_surface_fps']._loaded_options = None
  _globals['_FRAMETIMES'].fields_by_name['avg_surface_fps']._serialized_options = b'\212\265\030\027unitless_biggerIsBetter'
  _globals['_FRAMETIMES'].fields_by_name['exp_avg_surface_fps']._loaded_options = None
  _globals['_FRAMETIMES'].fields_by_name['exp_avg_surface_fps']._serialized_options = b'\212\265\030\027unitless_biggerIsBetter'
  _globals['_FRAMETIMES']._serialized_start=116
  _globals['_FRAMETIMES']._serialized_end=332
# @@protoc_insertion_point(module_scope)
