# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/chrome/long_latency.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/chrome/long_latency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1protos/perfetto/metrics/chrome/long_latency.proto\x12\x0fperfetto.protos\"\xab\x01\n\x11\x43hromeLongLatency\x12\x44\n\x0clong_latency\x18\x01 \x03(\x0b\x32..perfetto.protos.ChromeLongLatency.LongLatency\x1aP\n\x0bLongLatency\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x14\n\x0cprocess_name\x18\x03 \x01(\t\x12\x0b\n\x03pid\x18\x04 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.chrome.long_latency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHROMELONGLATENCY']._serialized_start=71
  _globals['_CHROMELONGLATENCY']._serialized_end=242
  _globals['_CHROMELONGLATENCY_LONGLATENCY']._serialized_start=162
  _globals['_CHROMELONGLATENCY_LONGLATENCY']._serialized_end=242
# @@protoc_insertion_point(module_scope)
