# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/chrome/test_chrome_metric.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/chrome/test_chrome_metric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.perfetto.metrics import custom_options_pb2 as protos_dot_perfetto_dot_metrics_dot_custom__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7protos/perfetto/metrics/chrome/test_chrome_metric.proto\x12\x0fperfetto.protos\x1a,protos/perfetto/metrics/custom_options.proto\"A\n\x10TestChromeMetric\x12-\n\ntest_value\x18\x01 \x01(\x03\x42\x19\x8a\xb5\x18\x15\x63ount_smallerIsBetter')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.chrome.test_chrome_metric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTCHROMEMETRIC'].fields_by_name['test_value']._loaded_options = None
  _globals['_TESTCHROMEMETRIC'].fields_by_name['test_value']._serialized_options = b'\212\265\030\025count_smallerIsBetter'
  _globals['_TESTCHROMEMETRIC']._serialized_start=122
  _globals['_TESTCHROMEMETRIC']._serialized_end=187
# @@protoc_insertion_point(module_scope)
