# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/metrics/chrome/unsymbolized_args.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/metrics/chrome/unsymbolized_args.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6protos/perfetto/metrics/chrome/unsymbolized_args.proto\x12\x0fperfetto.protos\"\xa7\x01\n\x16\x43hromeUnsymbolizedArgs\x12\x39\n\x04\x61rgs\x18\x01 \x03(\x0b\x32+.perfetto.protos.ChromeUnsymbolizedArgs.Arg\x1aR\n\x03\x41rg\x12\x0e\n\x06module\x18\x01 \x01(\t\x12\x10\n\x08\x62uild_id\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\x03\x12\x18\n\x10google_lookup_id\x18\x04 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.metrics.chrome.unsymbolized_args_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHROMEUNSYMBOLIZEDARGS']._serialized_start=76
  _globals['_CHROMEUNSYMBOLIZEDARGS']._serialized_end=243
  _globals['_CHROMEUNSYMBOLIZEDARGS_ARG']._serialized_start=161
  _globals['_CHROMEUNSYMBOLIZEDARGS_ARG']._serialized_end=243
# @@protoc_insertion_point(module_scope)
