# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/perfetto/ipc/relay_port.proto
# Protobuf Python Version: 5.27.3
'''Generated protocol buffer code.'''
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'protos/perfetto/ipc/relay_port.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$protos/perfetto/ipc/relay_port.proto\x12\x0fperfetto.protos\"\xd0\x01\n\x10SyncClockRequest\x12\x36\n\x05phase\x18\x01 \x01(\x0e\x32\'.perfetto.protos.SyncClockRequest.Phase\x12\x37\n\x06\x63locks\x18\x02 \x03(\x0b\x32\'.perfetto.protos.SyncClockRequest.Clock\x1a,\n\x05\x43lock\x12\x10\n\x08\x63lock_id\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\"\x1d\n\x05Phase\x12\x08\n\x04PING\x10\x01\x12\n\n\x06UPDATE\x10\x02\"\x13\n\x11SyncClockResponse2a\n\tRelayPort\x12T\n\tSyncClock\x12!.perfetto.protos.SyncClockRequest\x1a\".perfetto.protos.SyncClockResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.perfetto.ipc.relay_port_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNCCLOCKREQUEST']._serialized_start=58
  _globals['_SYNCCLOCKREQUEST']._serialized_end=266
  _globals['_SYNCCLOCKREQUEST_CLOCK']._serialized_start=191
  _globals['_SYNCCLOCKREQUEST_CLOCK']._serialized_end=235
  _globals['_SYNCCLOCKREQUEST_PHASE']._serialized_start=237
  _globals['_SYNCCLOCKREQUEST_PHASE']._serialized_end=266
  _globals['_SYNCCLOCKRESPONSE']._serialized_start=268
  _globals['_SYNCCLOCKRESPONSE']._serialized_end=287
  _globals['_RELAYPORT']._serialized_start=289
  _globals['_RELAYPORT']._serialized_end=386
# @@protoc_insertion_point(module_scope)
